// Generated by CoffeeScript 1.9.2
var Cell, Editor, MaxPositive, Row, Table, link, table;

MaxPositive = function(list) {
  return Math.max.apply(this, [0].concat(list));
};

Table = (function() {
  function Table() {
    this.dom = document.createElement("table");
    this.rows = [];
    this.editor = new Editor;
  }

  Table.prototype.AddRow = function() {
    var i, r, ref, row;
    row = new Row(this);
    for (i = 1, ref = MaxPositive((function() {
      var j, len, ref1, results;
      ref1 = this.rows;
      results = [];
      for (j = 0, len = ref1.length; j < len; j++) {
        r = ref1[j];
        results.push(r.cells.length);
      }
      return results;
    }).call(this)); i <= ref; i += 1) {
      row.AddCell();
    }
    this.rows.push(row);
  };

  Table.prototype.AddColumn = function() {
    var i, len, ref, row;
    ref = this.rows;
    for (i = 0, len = ref.length; i < len; i++) {
      row = ref[i];
      row.AddCell();
    }
  };

  Table.prototype.FillCell = function(row, col, text) {
    this.rows[row].cells[col].FillWith(text);
  };

  Table.prototype.ValueOfCell = function(row, col) {
    return this.rows[row].cells[col].Value();
  };

  Table.prototype.InsertIntoPageAt = function(element) {
    element.appendChild(this.dom);
    this.editor.InsertIntoPageAt(element);
  };

  return Table;

})();

Row = (function() {
  function Row(table) {
    this.dom = table.dom.insertRow();
    this.cells = [];
    this.editor = table.editor;
  }

  Row.prototype.AddCell = function() {
    var cell;
    cell = new Cell(this);
    this.cells.push(cell);
  };

  return Row;

})();

Cell = (function() {
  function Cell(row) {
    this.dom = row.dom.insertCell();
    this.dom.classList.add("lst_cell");
    this.dom.addEventListener("dblclick", row.editor.ShowFor(this));
  }

  Cell.prototype.FillWith = function(text) {
    var content;
    while (this.dom.firstChild != null) {
      this.dom.removeChild(this.dom.firstChild);
    }
    content = document.createTextNode(text);
    this.dom.appendChild(content);
  };

  Cell.prototype.Value = function() {
    var ref;
    return ((ref = this.dom.firstChild) != null ? ref.nodeValue : void 0) || "";
  };

  return Cell;

})();

Editor = (function() {
  function Editor() {
    this.CommitAndHide = this.CommitAndHideGenerator();
    this.RevertAndHide = this.RevertAndHideGenerator();
    this.KeyHandler = this.KeyHandlerGenerator();
    this.dom = document.createElement("textarea");
    this.dom.style.position = "absolute";
    this.dom.style.visibility = "hidden";
    this.dom.addEventListener("blur", this.CommitAndHide);
    this.dom.addEventListener("keydown", this.KeyHandler);
    this.cell = null;
  }

  Editor.prototype.InsertIntoPageAt = function(element) {
    element.appendChild(this.dom);
  };

  Editor.prototype.ShowFor = function(cell) {
    var editor;
    editor = this;
    return function() {
      editor.dom.value = cell.Value();
      editor.dom.style.top = cell.dom.offsetTop + "px";
      editor.dom.style.left = cell.dom.offsetLeft + "px";
      editor.dom.style.visibility = "visible";
      editor.dom.focus();
      editor.cell = cell;
    };
  };

  Editor.prototype.CommitAndHideGenerator = function() {
    var editor;
    editor = this;
    return function() {
      var ref;
      if ((ref = editor.cell) != null) {
        ref.FillWith(editor.dom.value);
      }
      editor.cell = null;
      editor.dom.style.visibility = "hidden";
    };
  };

  Editor.prototype.RevertAndHideGenerator = function() {
    var editor;
    editor = this;
    return function() {
      editor.cell = null;
      editor.dom.style.visibility = "hidden";
    };
  };

  Editor.prototype.KeyHandlerGenerator = function() {
    var editor;
    editor = this;
    return function(event) {
      var key;
      if (event.defaultPrevented) {
        return;
      }
      key = event.key || event.keyCode;
      switch (key) {
        case "Enter":
        case 13:
          editor.CommitAndHide();
          event.preventDefault();
          break;
        case "Escape":
        case 27:
          editor.RevertAndHide();
          event.preventDefault();
      }
    };
  };

  return Editor;

})();

table = new Table;

table.AddRow();

table.AddRow();

table.AddRow();

table.AddColumn();

table.AddColumn();

table.FillCell(0, 0, "X1");

table.FillCell(1, 0, "X2");

table.FillCell(2, 0, "X3");

table.InsertIntoPageAt(document.body);

link = document.createElement("a");

link.appendChild(document.createTextNode("test"));

link.addEventListener("click", function() {
  return console.log(table.ValueOfCell(1, 0));
});

link.href = "\#";

document.body.appendChild(link);
